\documentclass[12pt]{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\usepackage{graphicx}
\usepackage{amsmath}
\usepackage[margin=1in]{geometry}
\usepackage{fancyhdr}
\usepackage{enumerate}
\usepackage[shortlabels]{enumitem}
\usepackage[spanish]{babel}
\usepackage{xurl}
\usepackage{tcolorbox}
\usepackage{titlesec}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{pgfplots}
\usepackage{tikz}
\usepackage{cancel}
\usepackage[hidelinks]{hyperref}

\titleclass{\subsubsubsection}{straight}[\subsection]

\newcounter{subsubsubsection}[subsubsection]
\renewcommand\thesubsubsubsection{\thesubsubsection.\arabic{subsubsubsection}}
\renewcommand\theparagraph{\thesubsubsubsection.\arabic{paragraph}} % optional; useful if paragraphs are to be numbered

\titleformat{\subsubsubsection}
{\normalfont\normalsize\bfseries}{\thesubsubsubsection}{1em}{}
\titlespacing*{\subsubsubsection}
{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}

\makeatletter
\renewcommand\paragraph{\@startsection{paragraph}{5}{\z@}%
  {3.25ex \@plus1ex \@minus.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries}}
\renewcommand\subparagraph{\@startsection{subparagraph}{6}{\parindent}%
  {3.25ex \@plus1ex \@minus .2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries}}
\def\toclevel@subsubsubsection{4}
\def\toclevel@paragraph{5}
% \def\toclevel@paragraph{6}
\def\toclevel@subparagraph{6}
\def\l@subsubsubsection{\@dottedtocline{4}{7em}{4em}}
\def\l@paragraph{\@dottedtocline{5}{10em}{5em}}
\def\l@subparagraph{\@dottedtocline{6}{14em}{6em}}
\makeatother

\setcounter{secnumdepth}{4}
\setcounter{tocdepth}{4}

% Set up headers and footers
\pagestyle{fancy}
\fancyhf{}  % Clear previous settings

\fancyhead[L]{Julián - Ludwig}
\fancyhead[C]{Taller 2 - Sim Estocástica}
\fancyhead[R]{\today}

\fancyfoot[C]{\thepage}
\fancyfoot[C]{\footnotesize Este trabajo está bajo una licencia CC BY-SA 4.0. Más info: \url{https://creativecommons.org/licenses/by/4.0/}}

\renewcommand{\headrulewidth}{0.2pt}


% Define R Style for listings
\lstdefinestyle{RStyle}{
  language=R,
  basicstyle=\ttfamily\small,
  keywordstyle=\color{blue}\bfseries,
  commentstyle=\color{green!40!black}\itshape,
  stringstyle=\color{red!70!black},
  numbers=left,
  numberstyle=\tiny\color{gray},
  stepnumber=1,
  numbersep=5pt,
  backgroundcolor=\color{gray!10},
  showstringspaces=false,
  breaklines=true,
  frame=single,
  rulecolor=\color{black},
  captionpos=b,
  morekeywords={generator}
}

% Set RStyle as default
\lstset{style=RStyle}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\section{Stopping generating new simulation data}

Write a program to generate standard normal random variables until you have generated n of them, where $n \geq 100$ is such that $S/\sqrt{n} < 0.01$, where S is the sample standard deviation of the n data values. Note that this is the ``Method for Determining When to Stop Generating New Data''. Also, answer the following questions:



Debido a que se va a generar variables aleatorias \textbf{normales estándar} $X_{i}$, es decir, $X_{i} \sim \mathcal{N}(0, 1)$ y se debe parar de generar cuando $\frac{S}{\sqrt{n}} < 0.01$.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{x} \hlkwb{<-} \hlkwd{numeric}\hldef{()}
\hldef{s} \hlkwb{<-} \hlnum{1}
\hldef{n} \hlkwb{<-} \hlnum{0}

\hlkwa{while}\hldef{(n} \hlopt{<} \hlnum{100} \hlopt{||} \hldef{s} \hlopt{/} \hlkwd{sqrt}\hldef{(n)} \hlopt{>=} \hlnum{0.01}\hldef{) \{}
  \hldef{x} \hlkwb{<-} \hlkwd{c}\hldef{(x,} \hlkwd{rnorm}\hldef{(}\hlnum{1}\hldef{))}
  \hldef{n} \hlkwb{<-} \hlkwd{length}\hldef{(x)}
  \hldef{s} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
\hldef{\}}

\hlkwd{cat}\hldef{(}\hlsng{"Cantidad de Xi generados"}\hldef{, n,} \hlsng{"\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Cantidad de Xi generados 10208
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hldef{(}\hlsng{"Desviación estándar"}\hldef{,} \hlkwd{round}\hldef{(s,} \hlnum{5}\hldef{),} \hlsng{"\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Desviación estándar 1.01027
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hldef{(}\hlsng{"Error estándar S/sqrt(n)"}\hldef{,} \hlkwd{round}\hldef{(s}\hlopt{/}\hlkwd{sqrt}\hldef{(n),} \hlnum{5}\hldef{),} \hlsng{"\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Error estándar S/sqrt(n) 0.01
\end{verbatim}
\end{kframe}
\end{knitrout}


En el código se declara una variable $s$ inicializada en 1 para que luego sea nuevamente computada a la desviación estándar de $x$ que es un vector que va a almacenar todas las variables normales aleatorias generadas. Según el enunciado tenemos una condición de que al menos deben haber 100 variables aleatorias generadas ($n \geq 100$) y que el error estándar sea menor a 0.01 ($S / \sqrt{n} < 0.01$). En el ciclo \lstinline|while|, por lo tanto, tiene sentido que el ciclo continue si alguna de las afirmaciones anteriores son falsas, por eso queda la condición de esa manera. Se hace uso de la función \lstinline|rnorm(1)| para que genere una variable aleatoria normal con los valores por defecto (promedio 0 y desviación 1). 






\subsection{How many normals do you think will be generated? Give an analytic estimate.}
\label{subsec:p1-a}

\subsubsection{Respuesta}

Aunque ya se tengan los resultados de la simulación, se puede hacer un estimado analítico con la condición $S / \sqrt{n} < 0.01$ donde se puede despejar $n$ para saber cuántas variables se necesitan para parar el criterio.

Se tiene en primer lugar la inecuación:

\[
\frac{S}{\sqrt{n}} < 0.01
\]

Se eleva ambas partes con menos 1:

\begin{align*}
  \left(\frac{S}{\sqrt{n}}  \right)^{-1} &> 0.01^{-1} \\
  \frac{\sqrt{n}}{S}  &> 100
\end{align*}

Multiplicando ambas partes por $S$:

\begin{align*}
  \cancel{S} \times \frac{\sqrt{n}}{\cancel{S}}  &> 100 \times S \\
  \sqrt{n} &> 100 \times S 
\end{align*}

Ahora se cancela la raíz elevando ambas partes al cuadrado:

\begin{align*}
  (\cancel{\sqrt{n}})^{\cancel{2}} &> (100 \times S)^{2} 
\end{align*}

Quedando entonces:

\[
n > 10000\times S^{2}
\]

Para hacer el ejercicio se utilizó en \textsf{R} la función \texttt{rnorm(1, mean = 0, sd = 1)}, de esta manera genera únicamente 1 valor con media 0 y desviación 1, por lo tanto, podemos hacer $S = 1$ para estimar cuántos $n$ necesitamos para que se cumpla condición y deje de generar variables aleatorias, por lo tanto:

\begin{align*}
  n &> 10000 \times (1)^{2} \\
  n &> 10000 
\end{align*}

Este valor se acerca bastante al que se imprime en la simulación. 











\subsection{How many normals did you generate?}
\label{subsec:p1-b}

\subsubsection{Respuesta}

Se han generado \lstinline|n=| $10208$ normales.


\subsection{What is the sample mean of all the normals generated?}
\label{subsec:p1-c}




\subsubsection{Respuesta}

Utilizando el comando \lstinline|mean()| al vector \lstinline|x| se obtiene $0.0182439$. 

\subsection{What is the sample variance?}
\label{subsec:p1-d}


\subsubsection{Respuesta}

La varianza muestral se calcula como:

\[
S^{2} = \frac{\sum_{i=1}^{n} (X_{i} - \bar{X})^{2}}{n-1}
\]

Esto se puede sacar con la función \lstinline|var()| de \textsf{R}, por lo tanto, aplicando eso al vector \lstinline|x| se obtiene $1.0206531$.



\subsection{Comment on the results of (\ref{subsec:p1-c}) and (\ref{subsec:p1-d}). Were they surprising?}
\label{subsec:p1-e}

\subsubsection{Respuesta}

El resultado de \ref{subsec:p1-c} es la media de \lstinline|x| que es $0.0182439$ y el de \ref{subsec:p1-d} es la varianza muestral de \lstinline|x| dando $1.0206531$. Estos valores muy sorprendentes no fueron... Se espera que al simular muchas veces una distribución normal, esta nos dé los valores de la media y la desviación estándar al cuadrado. Pero sí es interesante que dado este algoritmo para detenerse después de cruzar un $S / \sqrt{n}$ nos dé valores muy cercanos a una distribución normal con $\mu = 0$ y $\sigma = 1$.


\newpage

\section{Gaining confidence with confidence intervals}

We know that the $\mathcal{U}(-1, 1)$ r.v. has mean 0. Use a sample of size $1000$ to estimate the mean and give a $95\%$ confidence interval (CI). Does the CI contain 0? Repeat the above a large number of times ($\geq  100$). What percentage of time does the CI contain 0? Write your code so that it produces output similar to the following:

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.6\textwidth]{img/Punto2.png}
\end{figure}

\subsection{Respuesta}

Se sabe que para tener un intervalo de confianza de 95\%, el límite inferior y superior serán, respectivamente:

\[
\left( \bar{X} - 1.96 \frac{S}{\sqrt{n}}, \bar{X} + 1.96 \frac{S}{\sqrt{n}} \right)
\]

El siguiente código permite sacar el intervalo de confianza del 95\% y también el estimado de la media.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{n} \hlkwb{<-} \hlnum{1000}
\hldef{x} \hlkwb{<-} \hlkwd{runif}\hldef{(n,} \hlopt{-}\hlnum{1}\hldef{,} \hlnum{1}\hldef{)}
\hldef{xmean} \hlkwb{<-} \hlkwd{mean}\hldef{(x)}
\hldef{S} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
\hldef{L} \hlkwb{<-} \hldef{xmean} \hlopt{-} \hlnum{1.96} \hlopt{*} \hldef{S}\hlopt{/}\hlkwd{sqrt}\hldef{(n)}
\hldef{U} \hlkwb{<-} \hldef{xmean} \hlopt{+} \hlnum{1.96} \hlopt{*} \hldef{S}\hlopt{/}\hlkwd{sqrt}\hldef{(n)}
\hlkwd{cat}\hldef{(}\hlsng{"El estimado es"}\hldef{, xmean,} \hlsng{"\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## El estimado es 0.01303919
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hldef{(}\hlsng{"95% está entre ("}\hldef{, L,} \hlsng{", "}\hldef{, U,} \hlsng{") \textbackslash{}n"}\hldef{,} \hlkwc{sep}\hldef{=}\hlsng{""}\hldef{)}
\end{alltt}
\begin{verbatim}
## 95% está entre (-0.02297891, 0.04905728)
\end{verbatim}
\end{kframe}
\end{knitrout}

Aquí se estimó la media de la distribución uniforme, dando un resultado de $0.0130392$, muy cercano a 0. El intervalo de confianza está entre $-0.0229789$ y $0.0490573$, en este caso sí contiene a 0.\footnote{Aquí hay que hacer una aclaración, los autores utilizaron \href{https://yihui.org/knitr/}{knitr}, una herramienta para la generación de reportes dinámicos en \textsf{R}, entonces cada vez que se compile este archivo \texttt{.Rnw} va a salir una salida diferente y puede ser que ya el intervalo no contenga 0.} Ahora, se va a realizar el proceso unas 200 veces para conocer el porcentaje de intervalos de confianza que contienen 0.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{trials} \hlkwb{<-} \hlnum{200}
\hldef{n} \hlkwb{<-} \hlnum{1000}
\hldef{true_mean} \hlkwb{<-} \hlnum{0}

\hldef{results} \hlkwb{<-} \hlkwd{data.frame}\hldef{(}
  \hlkwc{sample_mean} \hldef{=} \hlkwd{numeric}\hldef{(trials),}
  \hlkwc{lower_bound} \hldef{=} \hlkwd{numeric}\hldef{(trials),}
  \hlkwc{upper_bound} \hldef{=} \hlkwd{numeric}\hldef{(trials),}
  \hlkwc{contains_mean} \hldef{=} \hlkwd{integer}\hldef{(trials)}
\hldef{)}

\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{trials)\{}
  \hldef{x} \hlkwb{<-} \hlkwd{runif}\hldef{(n,} \hlopt{-}\hlnum{1}\hldef{,} \hlnum{1}\hldef{)}
  \hldef{xmean} \hlkwb{<-} \hlkwd{mean}\hldef{(x)}
  \hldef{S} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
  \hldef{L} \hlkwb{<-} \hldef{xmean} \hlopt{-} \hlnum{1.96} \hlopt{*} \hldef{S}\hlopt{/}\hlkwd{sqrt}\hldef{(n)}
  \hldef{U} \hlkwb{<-} \hldef{xmean} \hlopt{+} \hlnum{1.96} \hlopt{*} \hldef{S}\hlopt{/}\hlkwd{sqrt}\hldef{(n)}
  \hldef{contains} \hlkwb{<-} \hlkwd{as.integer}\hldef{(L} \hlopt{<=} \hldef{true_mean} \hlopt{&} \hldef{true_mean} \hlopt{<=} \hldef{U)}

  \hldef{results[i, ]} \hlkwb{<-} \hlkwd{c}\hldef{(xmean, L, U, contains)}
\hldef{\}}

\hlkwd{cat}\hldef{(}\hlsng{"Número de intentos:"}\hldef{, trials,} \hlsng{"\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Número de intentos: 200
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hldef{(results,} \hlkwc{digits}\hldef{=} \hlnum{4}\hldef{)}
\end{alltt}
\begin{verbatim}
##     sample_mean lower_bound upper_bound contains_mean
## 1     3.378e-02   -0.001630   0.0691830             1
## 2     9.178e-04   -0.035414   0.0372494             1
## 3     2.345e-02   -0.012044   0.0589491             1
## 4    -1.357e-02   -0.048499   0.0213639             1
## 5    -1.131e-02   -0.047382   0.0247666             1
## 6    -2.371e-03   -0.038327   0.0335849             1
## 7     9.427e-03   -0.025923   0.0447769             1
## 8    -1.780e-02   -0.054556   0.0189601             1
## 9    -4.779e-03   -0.040663   0.0311050             1
## 10   -2.338e-02   -0.059004   0.0122487             1
## 11    1.148e-02   -0.023961   0.0469112             1
## 12    1.426e-02   -0.021412   0.0499352             1
## 13   -4.693e-03   -0.040345   0.0309590             1
## 14   -1.974e-02   -0.054846   0.0153653             1
## 15   -3.806e-03   -0.040645   0.0330335             1
## 16   -1.082e-02   -0.047269   0.0256361             1
## 17   -1.095e-02   -0.046611   0.0247089             1
## 18    9.152e-03   -0.026641   0.0449438             1
## 19   -1.239e-02   -0.049192   0.0244096             1
## 20   -2.108e-02   -0.056647   0.0144887             1
## 21    5.638e-03   -0.029012   0.0402877             1
## 22   -5.897e-04   -0.035707   0.0345273             1
## 23    3.454e-02   -0.002033   0.0711073             1
## 24    1.767e-02   -0.018224   0.0535583             1
## 25   -2.015e-02   -0.055702   0.0154090             1
## 26   -5.802e-03   -0.042489   0.0308854             1
## 27    1.704e-02   -0.019178   0.0532538             1
## 28    2.482e-02   -0.010642   0.0602866             1
## 29   -2.107e-02   -0.056199   0.0140652             1
## 30   -7.713e-03   -0.043599   0.0281724             1
## 31    7.656e-03   -0.028280   0.0435911             1
## 32   -1.644e-02   -0.052929   0.0200456             1
## 33   -2.096e-02   -0.056851   0.0149407             1
## 34    1.518e-03   -0.033969   0.0370046             1
## 35   -5.520e-03   -0.042274   0.0312330             1
## 36    8.276e-04   -0.034227   0.0358823             1
## 37   -4.319e-03   -0.040025   0.0313882             1
## 38   -2.104e-02   -0.057075   0.0149929             1
## 39   -1.788e-02   -0.053330   0.0175771             1
## 40   -7.543e-03   -0.044055   0.0289679             1
## 41   -1.703e-02   -0.052368   0.0183139             1
## 42    8.622e-03   -0.027189   0.0444338             1
## 43   -1.685e-02   -0.052794   0.0191019             1
## 44   -7.096e-03   -0.043023   0.0288314             1
## 45    2.171e-02   -0.013053   0.0564647             1
## 46   -3.123e-03   -0.038889   0.0326424             1
## 47    2.749e-02   -0.007962   0.0629453             1
## 48   -4.653e-02   -0.082445  -0.0106099             0
## 49    1.818e-02   -0.018534   0.0548907             1
## 50   -6.221e-03   -0.041903   0.0294610             1
## 51   -2.845e-03   -0.038588   0.0328980             1
## 52    3.051e-02   -0.005573   0.0665942             1
## 53    4.716e-03   -0.030224   0.0396559             1
## 54   -6.076e-03   -0.041786   0.0296350             1
## 55    1.774e-02   -0.018529   0.0540104             1
## 56    2.685e-02   -0.008827   0.0625314             1
## 57   -6.283e-03   -0.041663   0.0290984             1
## 58    9.015e-03   -0.026952   0.0449824             1
## 59   -8.256e-03   -0.045192   0.0286807             1
## 60    2.477e-02   -0.011053   0.0605844             1
## 61    1.150e-02   -0.023628   0.0466177             1
## 62    4.241e-04   -0.035479   0.0363273             1
## 63    2.393e-02   -0.011192   0.0590573             1
## 64   -1.115e-02   -0.047221   0.0249268             1
## 65   -3.101e-03   -0.039142   0.0329410             1
## 66    4.537e-04   -0.035291   0.0361983             1
## 67   -2.326e-02   -0.059570   0.0130562             1
## 68    2.528e-02   -0.010550   0.0611110             1
## 69    1.670e-02   -0.019090   0.0524927             1
## 70    8.319e-03   -0.027667   0.0443048             1
## 71    1.026e-02   -0.025330   0.0458501             1
## 72   -1.613e-02   -0.051458   0.0192038             1
## 73   -2.262e-02   -0.058705   0.0134699             1
## 74    2.704e-02   -0.009048   0.0631372             1
## 75    1.904e-03   -0.033824   0.0376332             1
## 76    1.480e-02   -0.021314   0.0509080             1
## 77    2.233e-02   -0.012640   0.0572964             1
## 78   -6.468e-03   -0.041472   0.0285374             1
## 79    5.591e-03   -0.030334   0.0415171             1
## 80   -2.116e-02   -0.056187   0.0138622             1
## 81   -1.413e-02   -0.050389   0.0221219             1
## 82    8.555e-04   -0.034889   0.0366001             1
## 83    1.575e-02   -0.019633   0.0511420             1
## 84    1.799e-02   -0.018217   0.0541920             1
## 85   -1.496e-02   -0.050997   0.0210768             1
## 86    2.502e-02   -0.009870   0.0599033             1
## 87   -2.121e-02   -0.057042   0.0146317             1
## 88    2.445e-02   -0.010986   0.0598783             1
## 89   -2.232e-02   -0.058452   0.0138146             1
## 90   -2.259e-02   -0.058238   0.0130533             1
## 91    5.809e-03   -0.029720   0.0413385             1
## 92    3.881e-02    0.002783   0.0748374             0
## 93    1.780e-02   -0.018387   0.0539788             1
## 94   -8.479e-03   -0.044257   0.0273000             1
## 95   -1.803e-02   -0.054252   0.0181902             1
## 96    1.230e-02   -0.024076   0.0486767             1
## 97    1.782e-02   -0.017761   0.0533987             1
## 98   -3.568e-02   -0.070996  -0.0003581             0
## 99   -8.930e-03   -0.044411   0.0265499             1
## 100   1.900e-03   -0.034136   0.0379353             1
## 101   2.461e-03   -0.032674   0.0375954             1
## 102   7.301e-03   -0.029178   0.0437797             1
## 103  -9.189e-03   -0.044737   0.0263592             1
## 104  -1.883e-02   -0.054280   0.0166215             1
## 105  -2.680e-02   -0.062038   0.0084407             1
## 106  -3.301e-02   -0.069286   0.0032695             1
## 107   3.671e-03   -0.031615   0.0389564             1
## 108   1.875e-02   -0.016278   0.0537746             1
## 109  -7.507e-05   -0.035642   0.0354922             1
## 110  -1.046e-02   -0.045581   0.0246662             1
## 111  -1.094e-03   -0.036799   0.0346112             1
## 112  -9.853e-03   -0.045395   0.0256888             1
## 113  -1.480e-02   -0.050434   0.0208298             1
## 114   6.108e-03   -0.029465   0.0416817             1
## 115  -3.480e-02   -0.070152   0.0005448             1
## 116  -9.451e-03   -0.045223   0.0263197             1
## 117  -2.458e-03   -0.037744   0.0328266             1
## 118   9.135e-03   -0.026644   0.0449149             1
## 119  -2.983e-02   -0.065344   0.0056823             1
## 120  -1.469e-02   -0.050640   0.0212638             1
## 121  -2.785e-03   -0.039086   0.0335153             1
## 122   1.301e-02   -0.022285   0.0483091             1
## 123  -9.777e-03   -0.044909   0.0253540             1
## 124  -2.357e-03   -0.039227   0.0345133             1
## 125   3.363e-02   -0.001789   0.0690406             1
## 126  -5.599e-03   -0.042403   0.0312048             1
## 127  -2.839e-02   -0.063637   0.0068661             1
## 128   1.056e-03   -0.034809   0.0369205             1
## 129  -2.042e-02   -0.055848   0.0150008             1
## 130  -6.412e-03   -0.042154   0.0293292             1
## 131  -4.844e-03   -0.039839   0.0301505             1
## 132   2.840e-02   -0.007113   0.0639168             1
## 133   6.406e-03   -0.029491   0.0423032             1
## 134   7.890e-03   -0.028157   0.0439371             1
## 135   1.198e-02   -0.023848   0.0478099             1
## 136   1.138e-03   -0.034188   0.0364635             1
## 137  -3.476e-02   -0.070516   0.0009978             1
## 138   1.549e-02   -0.020932   0.0519112             1
## 139   1.912e-02   -0.016841   0.0550766             1
## 140   2.690e-02   -0.008607   0.0624084             1
## 141   1.137e-02   -0.024148   0.0468914             1
## 142  -8.682e-04   -0.036271   0.0345344             1
## 143  -5.232e-03   -0.041316   0.0308524             1
## 144   3.758e-03   -0.032049   0.0395659             1
## 145  -8.456e-04   -0.036941   0.0352495             1
## 146   2.805e-02   -0.007718   0.0638224             1
## 147   3.354e-03   -0.032598   0.0393054             1
## 148  -2.727e-04   -0.036326   0.0357805             1
## 149  -7.633e-03   -0.043634   0.0283684             1
## 150   1.122e-02   -0.024868   0.0473100             1
## 151   2.223e-02   -0.013597   0.0580554             1
## 152  -1.899e-02   -0.054792   0.0168206             1
## 153   3.092e-02   -0.004596   0.0664317             1
## 154   1.738e-02   -0.018796   0.0535550             1
## 155   4.692e-03   -0.031542   0.0409262             1
## 156   2.120e-02   -0.014697   0.0571010             1
## 157  -3.059e-03   -0.039476   0.0333569             1
## 158  -1.843e-02   -0.053817   0.0169592             1
## 159  -4.151e-03   -0.039230   0.0309289             1
## 160  -3.964e-03   -0.040009   0.0320811             1
## 161  -9.906e-03   -0.045264   0.0254525             1
## 162   3.659e-03   -0.031261   0.0385792             1
## 163   2.086e-04   -0.036409   0.0368261             1
## 164  -1.340e-02   -0.048616   0.0218167             1
## 165   5.692e-03   -0.030156   0.0415389             1
## 166  -1.259e-02   -0.047858   0.0226780             1
## 167  -3.910e-02   -0.074962  -0.0032302             0
## 168  -5.450e-03   -0.040671   0.0297706             1
## 169   2.695e-02   -0.008597   0.0624956             1
## 170   1.636e-02   -0.019342   0.0520595             1
## 171   1.996e-02   -0.016390   0.0563033             1
## 172   1.341e-02   -0.022756   0.0495852             1
## 173   1.855e-02   -0.018300   0.0553925             1
## 174  -6.428e-03   -0.041580   0.0287244             1
## 175  -9.256e-03   -0.045294   0.0267827             1
## 176   2.562e-03   -0.033000   0.0381240             1
## 177   4.379e-03   -0.030872   0.0396304             1
## 178   1.104e-02   -0.024801   0.0468852             1
## 179   3.453e-02   -0.001522   0.0705810             1
## 180   8.340e-03   -0.027146   0.0438266             1
## 181   8.340e-03   -0.026826   0.0435053             1
## 182   7.457e-03   -0.027708   0.0426225             1
## 183   1.743e-02   -0.017730   0.0525942             1
## 184   2.914e-03   -0.032717   0.0385443             1
## 185  -2.106e-02   -0.056455   0.0143288             1
## 186  -1.104e-02   -0.047217   0.0251437             1
## 187   4.729e-02    0.011347   0.0832317             0
## 188   1.452e-02   -0.020351   0.0493815             1
## 189  -1.616e-02   -0.051671   0.0193448             1
## 190   1.005e-03   -0.034422   0.0364314             1
## 191  -4.864e-03   -0.040587   0.0308594             1
## 192   2.007e-03   -0.033653   0.0376666             1
## 193  -1.860e-02   -0.054793   0.0175856             1
## 194   3.650e-02    0.001538   0.0714539             0
## 195   2.032e-02   -0.014762   0.0554067             1
## 196   9.487e-03   -0.026812   0.0457852             1
## 197   3.638e-04   -0.034637   0.0353643             1
## 198  -1.848e-02   -0.054438   0.0174714             1
## 199  -5.285e-03   -0.041242   0.0306718             1
## 200   3.038e-03   -0.032733   0.0388098             1
\end{verbatim}
\begin{alltt}
\hldef{porcentaje} \hlkwb{<-} \hlkwd{mean}\hldef{(results}\hlopt{$}\hldef{contains_mean)} \hlopt{*} \hlnum{100}

\hlkwd{cat}\hldef{(}\hlsng{"\textbackslash{}n"}\hldef{, porcentaje,} \hlsng{"% de los intervalos de"}\hldef{,}
\hlsng{"confianza contienen la media real\textbackslash{}n"}\hldef{)}
\end{alltt}
\begin{verbatim}
## 
##  97 % de los intervalos de confianza contienen la media real
\end{verbatim}
\end{kframe}
\end{knitrout}


En conclusión, el $97$ \% de los intervalos generados incluyen al 0.


\section{Standard deviation of a proportion}

Assume a manager is using the sample proportion $\hat{p}$ to estimate the proportion p of a new shipment of computer chips that are defective. He doesn’t know $p$ for this shipment, but in previous shipments it has been close to $0.01$, that is $1 \% $ of chips have been defective.

\subsection{If the manager wants the standard deviation of $\hat{p}$ to be about $0.02$, how large a sample should she take based on the assumption that the rate of defectives has not changed dramatically?}

En clase se vieron los estimadores de probabilidad, donde se quiere estimar

\[
  p = (P X \in A)
\]

Donde \(A\) es el subconjunto del espacio de estados de \(\Omega \) de \(X\). Es decir, para nuestro problema, este subconjunto de espacios en la muestra que tomó la administradora del cargamento de chips defectuosos. Se puede definir la variable indicadora \(Z\) como:

\[
  Z = 
  \begin{cases}
    1, & \quad X \in A \\
    0, & \quad X \notin A
  \end{cases}
\]

1 significa que sí está defectuoso y 0 que no lo está. Se puede escribir el estimador como:

\[
p = E[Z]
\]

En clase se realizó una demostración de como el valor esperado de \(Z\) se le puede asignar a \(p\). Se define la varianza de \(Z\) como:

\begin{align*}
\mathrm{Var}(Z) &= E[Z^{2}] - E[Z]^{2} \\
  &= (1^{2} \times P(X \in A) + 0^{2} \times P (X \notin A)) - (P(X \in A))^{²} \\
  &= p - p^{2}
\end{align*}

Aplicando factorización:

\[
\mathrm{Var}(Z) = p (1 - p)
\]

Estimar $p$ se puede realizar mediante el promedio muestral de $Z$, es decir, se puede estimar la proporción $\hat{p}$ con el promedio de los chips que son defectuosos:

\[
\hat{p} = \frac{1}{n} \sum_{i =1}^{n} Z_{i}
\]

Se puede calcular entonces, la varianza del estimador:

\[
\mathrm{Var}(\hat{p}) = \frac{1}{n} \mathrm{Var} \left(\sum_{i=1}^{n} Z_{i} \right)
\]

Por independencia de los valores del cargamento de chips $Z_{i}$ se puede meter la varianza de estos en la suma:

\begin{align*}
  \mathrm{Var}(\hat{p}) &= \frac{1}{n^{2}} \sum_{i=1}^{n} \mathrm{Var}(Z_{i}) \\
  &= \frac{1}{n^{2}} \sum_{i=1}^{n} p(1 - p) = \frac{1}{n} p (1 -p) 
\end{align*}

Por lo tanto, una aproximación es:

\[
\mathrm{Var}(\hat{p}) \approx \frac{1}{n} \hat{p} (1 - \hat{p}) 
\]

Teniendo en cuenta que la desviación estándar es el cuadrado de la varianza, se puede despejar:

\[
\sigma_{\hat{p}} \approx \sqrt{\frac{\hat{p} (1 - \hat{p})}{n}}
\]

El problema nos dice que la desviación estándar de $\hat{p}$ ($\sigma_{\hat{p}}$) debe ser sobre 0.02 y nos piden hallar cuántas muestras debe tomar la administradora, por lo tanto, en la parte izquierda de la ecuación reemplazamos por $0.02$, se despeja para $n$ y la proporción de defectuosos se toma como $0.01$ debido a que en el problema se nos dice que no ha cambiado tanto.

\begin{align*}
  \sigma_{\hat{p}} &\approx \sqrt{\frac{\hat{p} (1 - \hat{p})}{n}} \\
  0.02 &\approx \sqrt{\frac{0.1 (1 - 0.1)}{n}  } \\
  0.02 &\approx \sqrt{\frac{0.0099}{n}  } \\
  (0.02)^{2} &\approx \left(\cancel{\sqrt{\frac{0.0099}{n}  }} \right)^{\cancel{2}}\\
  0.0004 &\approx \frac{0.0099}{n} \\
  n &\approx \frac{0.0099}{0.0004} = 24.75
\end{align*}

Por lo tanto, la administradora debe tomar un muestra de por lo menos 25 chips para tener una desviación estándar de al menos $0.02$.

\subsection{Now suppose something went wrong with the production run and the actual proportion of defectives in the shipment is 0.3, that is 30 \% are defective. Now what would be the actual standard deviation of $\hat{p}$ for the sample size you choose in a)?}

Teniendo 25 chips y cambiando el valor de la proporción de defectuosos, se obtiene:

\begin{align*}
  \sigma_{\hat{p}} &\approx \sqrt{\frac{\hat{p}(1 - \hat{p}) }{n}} \\
                   &\approx   \sqrt{\frac{0.3(1 - 0.3) }{25}} \\
  &\approx 0.091
\end{align*}

Es decir, si la proporción de detección es del 30\%, la desviación estándar de $\hat{p}$ con una cantidad de chips de 25, será aproximadamente $0.091$.

\section{Bets}

You pay $10.000$ pesos to participate in a bet game, which consists in tossing two coins together. If two heads fall, you earn $15.000$ pesos. If one head and one tail fall you earn $5.000$ pesos. In any other case you earn nothing. Let $X$ the random variable of your profit.

\subsection{Analytically find the probability mass function $p_{X}$, the mean $E[X]$, and variance $\mathrm{Var}(X)$ of $X$.}

Dado que $X$ es la variable aleatoria de la ganancia, podemos listar los posibles valores que puede tomar de acuerdo a los lanzamientos:

\begin{table}[ht]
  \centering
  \begin{tabular}[h]{|c|c|}
    \hline
    \textbf{Salida moneda} & \textbf{Ganancia} \\ \hline
    HH & $15.000$ \\ \hline
    HT & $5.000$ \\ \hline
    TH & $5.000$ \\ \hline
    TT & $0$ \\ \hline 
  \end{tabular}
  \caption{Posibles salidas y ganancias al tirar dos monedas, (H) cara y (T) sello.}
  \label{tab:p3}
\end{table}

Del cuadro \ref{tab:p3} se toma que los posibles valores para las ganancias son:

\[
X \in \{0, 5000, 15000 \} 
\]

Debido a que se pueden lanzar dos monedas ($n = 2$), los lanzamientos son independientes entre ellos y la probabilidad de éxito es constante ($p = 0.5$), es decir, que salga cara en el lanzamiento. Debido a todo esto, se afirma que es una distribución binomial de la siguiente forma:

\[
p_{X} (x)  =
\begin{pmatrix}
  n \\ x
\end{pmatrix} p^{x} (1 - p)^{n-x}
\]

Reemplazando:

\[
p_{X} (x)  =
\begin{pmatrix}
  2 \\ x
\end{pmatrix} (0.5)^{x} (1 - 0.5)^{2-x}
\]

Para calcular el valor esperado de $X$:

\[
E[X] = \frac{1}{n} \sum_{i = 1}^{n} X_{i}
\]

Reemplazando: 

\[
E[X] = \frac{1}{3} \sum_{i = 1}^{3} X_{i} 
\]

Resolviendo:

\[
\frac{1}{3} \sum_{i = 1}^{3} X_{i} = \frac{0 + 5000 + 15000}{3}  = \frac{20000}{3} \approx 6666.67
\]

Ahora, para calcular la varianza se toma el valor esperado:

\begin{align*}
  \mathrm{Var}(X) &= E[X^{2}] - E[X]^{2} \\
  &= E[(0^{2}, 5000^{2}, 15000^{2})] - (6666.67)^{2}
\end{align*}








\end{document}
